name 'effortless-hoist'
version '1.0.0'
description 'utomatically hoist environment level-attributes from Policyfiles in the Effortless pattern'
maintainer 'Gregory Sloan'
maintainer_email 'swankgd@gmail.com'
license 'Apache-2.0'
source_url 'https://github.com/gsloan-chef/effortless-hoist'
issues_url 'https://github.com/gsloan-chef/effortless-hoist/issues'
chef_version '>= 12.2'
